stages:
  prepare:
    cmd: python scripts/simple_prepare.py
    deps:
      - scripts/simple_prepare.py
      - data/raw
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
      - metrics/data_metrics.json
  
  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
    outs:
      - models/best_model.pth
      - metrics/train_metrics.json
  
  embeddings:
    cmd: python scripts/create_embeddings.py
    deps:
      - scripts/create_embeddings.py
      - models/best_model.pth
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
    outs:
      - chroma_db
  
  report:
    cmd: python scripts/create_report.py
    deps:
      - metrics/data_metrics.json
      - metrics/train_metrics.json
      - chroma_db_info.json
    outs:
      - metrics/summary.json