stages:
  prepare:
    cmd: python scripts/prepare_data.py
    deps:
      - data/raw
      - scripts/prepare_data.py
    params:
      - prepare.split_ratio
      - prepare.image_size
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv

  train:
    cmd: python scripts/train_model.py
    deps:
      - data/processed/train.csv
      - data/processed/val.csv
      - scripts/train_model.py
    params:
      - train.batch_size
      - train.epochs
      - train.learning_rate
      - train.model_name
    outs:
      - models/best_model.pth
      - models/last_model.pth
    metrics:
      - metrics/train_metrics.json:
          cache: false