stages:
  prepare:
    cmd: python scripts/simple_prepare.py
    deps:
      - data/raw
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
      - data/processed/class_info.yaml
    metrics:
      - metrics/data_metrics.json

  train:
    cmd: python scripts/simple_train.py
    deps:
      - data/processed/train.csv
      - data/processed/val.csv
    outs:
      - models/best_model.pth
    metrics:
      - metrics/train_metrics.json

  report:
    cmd: python scripts/create_report.py
    deps:
      - metrics/data_metrics.json
      - metrics/train_metrics.json
    metrics:
      - metrics/summary.json
